spring.application.name=demo
server.port=8080
meta.api.token=EAAZAUaDdowWUBRJOmAFBj71p1EIdOub7DxaiMAmMZBfL8LZA2pOmrAXh5gx5pOh1w4vDb4K6yWZBM3fL4F08Tz8hNnBcqFZADt9l7Yk1JwrkKXJzak8FZCTcpQy6uTivhGUukYZAJKiQtVP2pZAQW6Uu3lSSZCKkWYPeiixRja7eqfIwDeuCZBReIQ3F9dnFduS8h8w3VRKwZAqdZCHZBUG3IzvKBxzPFqydwjuZCMqg9Pv0b7J1oQtV9E4NC57zEbXOrYkTG6sfoTPGFzPmjrXe1SKximG6gX
meta.phone.number.id=1094110330451683
meta.verify.token=healthbot_secret_2024

#claude.api.key=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
#claude.api.url=https://api.anthropic.com/v1/messages
# Remove claude lines and add:
gemini.api.key=AIzaSyAdN3Sd7CBib_GP3hOsA9WWAu_HPDhIo0I

aws.region=ap-south-1
aws.accessKeyId=AKIATQPD7S23TNDCA5YH
aws.secretAccessKey=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
aws.location.placeIndex=healthbot-place-index


spring.data.redis.host=picked-adder-71235.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAARZDAAIncDI5MGUxYjUzNDIxMDE0MGE5YWMzMjI4NWY2MmVkNWMzOXAyNzEyMzU
spring.data.redis.ssl.enabled=true
spring.data.redis.lettuce.pool.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/Learn
spring.datasource.username=postgres
spring.datasource.password=123
